src/components/Profile/Profile.tsx
src/components/Profile/ProfileSection.tsx
src/components/Profile/ProfileSectionItem.tsx
src/pages/Home.tsx

Implemented basic view to show profile data.

Show profile data

---

src/api/api.yaml
src/api/api_backoffice.yaml
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx

I fixed bugs related to changing salesChannel in the form.

PE-86 Fix sales channels

---

src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountConditions.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx
src/components/Form/CreateProfileForm/DiscountData/ProductCategories.tsx
src/components/Form/CreateProfileForm/DiscountData/StaticCode.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx
src/pages/CreateProfile.tsx

I fixed the forms related to discount management, correcting some issues on dates and other form fields.

Fix discounts profile form

---

src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Stepper/Stepper.tsx

I fixed the behaviour of the continue button for the discount form.

PE-89 fix active continue button

---

src/components/Stepper/Stepper.tsx

Fixed tab navigation at first access to block the user to navigate through all the steps without completing them.

PE-88 Fix tab navigation

---

src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/Documents.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/pages/CreateProfile.tsx

Fix checked steps to become checked only when I complete each step.

PE-93 Fix checked steps

---

src/pages/CreateProfile.tsx

Fix on linter

---

src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx

I fixed the creation of a new discount.

PE-102 Fix create new discount

---

src/components/Discounts/Discounts.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx

I fixed the edit discount data form.

Fix edit discount data

---

src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx

I fixed the edit operator data form.

Fix edit operator data form

---

src/pages/Login.tsx

I replaced the text of login page with the definitive text.

Fix login page text

---

package.json
src/api/api.yaml
src/api/api_backoffice.yaml
src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountConditions.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx
src/components/Form/CreateProfileForm/DiscountData/ProductCategories.tsx
src/components/Form/CreateProfileForm/DiscountData/StaticCode.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileDescription.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/ReferentData.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/CustomErrorMessage.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx
src/components/Form/EditProfileForm/EditProfileForm.tsx
src/components/Form/ValidationSchemas.ts
src/styles/bootstrap-italia-custom.scss
yarn.lock

I fixed the first part of some issues related to compilation requests

PE-93 fix compilation request

---

src/components/OperatorConvention/ConventionFilter.tsx
src/components/OperatorConvention/OperatorConvention.tsx
src/components/Requests/Requests.tsx
src/components/Requests/RequestsFilter.tsx

Add admin paginations

---

src/components/Discounts/Discounts.tsx
src/components/Discounts/PublishModal.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx

I added the button to publish a draft discount.

PE-114 fix publish button

---

src/components/Discounts/Discounts.tsx
src/components/Profile/Profile.tsx
src/components/ProfileData/ProfileData.tsx

I enabled the button only if the user is approved and I don't show them when he's pending.

PE-128 Disable crud pending agreeement

---

src/IDPS.ts

https://github.com/pagopa/hub-spid-login-ms/blob/74a197784600c940bdeda63224f6c818007adc8a/src/spid_const.ts#L1

fix IDPS entity

---

src/api/index.ts
src/components/Profile/Profile.tsx
src/components/Profile/ProfileApiToken.tsx

I added section relative to api validation token.

PE-18 api validation token

---

src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx

I fixed profile image behavior.

Fix profile image

---

src/components/AgreementState/AgreementState.tsx

Fixed the AgreementState component to show dates in correct format.

PE-132 Fix show data agreement state

---

src/components/Form/CreateProfileForm/DiscountData/ProductCategories.tsx

Fix product categories in FieldArray.

PE-125 Fix product categories

---

src/components/Form/ValidationSchemas.ts

I fixed the custom error message for discount type format.

PE-131 fix discount type format

---

src/components/Discounts/Discounts.tsx

I fixed the condition for visible icon to be visible or not.

PE-130 fix-visible-icon

---

src/api/api.yaml
src/components/Form/CreateProfileForm/Documents/FileRow.tsx
src/components/Profile/ProfileDocuments.tsx
src/utils/dates.tsx

Add documents date

---

src/components/Profile/ProfileDocuments.tsx

I fixed the get documents profile

PE-144-fix-get-documents-profile

---

src/components/Header/Header.tsx
src/components/Profile/ProfileDocuments.tsx

I added some fixes on dates, label and login button.

Fixes on dates, label and login button

---

src/components/Discounts/Discounts.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx
src/utils/strings.tsx

Fix edit discounts because it was not working due to routing.

PE-149 Fix edit discounts

---

src/components/Discounts/Discounts.tsx
src/components/Discounts/PublishModal.tsx

I fixed discount publish message

Fix discount publish message

---

src/components/Form/EditDiscountForm/EditDiscountForm.tsx

Fix publish button

---

src/components/Form/CreateProfileForm/Documents/RequestApproval.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx

I applied some correction of typos in the text.

Correction of typos in the text

---

src/components/Form/ValidationSchemas.ts

I fixed the validation conditions for website url to be correct.

PE-159 fix validation website url

---

src/components/Header/Header.tsx

I fixed the cursor to a hand when a non logged user open help link.

PE-161 fix cursor help link

---

src/components/Discounts/Discounts.tsx

I fixed the icon and the sorting for discount table.

PE-101 Fix show order column icon

---

src/components/Discounts/Discounts.tsx

I fixed the button to reactive expired discount.

PE-162 reactivate expired discount

---

package.json
src/components/Discounts/Discounts.tsx
src/components/Form/HelpForm/HelpForm.tsx
src/components/Form/ValidationSchemas.ts
src/components/Header/Header.tsx
yarn.lock

I implemented captcha verification for not logged user.

Implement captcha verification

---

src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx

I fixed address for both channels.

PE-164 Fix address both channels

---

src/components/Form/HelpForm/HelpForm.tsx

I fixed redirect rejected operator.

PE-169 fix redirect rejected operator

---

src/components/Form/CreateProfileForm/Documents/RequestApproval.tsx
src/pages/CreateProfile.tsx
src/styles/bootstrap-italia-custom.scss

I fixed redirect request approval.

PE-170 Fix-redirect-request-approval

---

src/api/api.yaml
src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx

I fixed the loader for the images.

PE-163-fix-image-loader

---

src/components/Form/EditProfileForm/EditProfileForm.tsx

PE-171-fix-update-profile-data

---

src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx

I fixed the address field to look up only places from Italy.

Implement search on italy

---

src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx

I implemented custom image errors.

PE-138 Implement custom image errors

---

src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/ProfileData/ProfileData.tsx

I fixed loading for first image.

Fix first image loading

---

.env.local
package.json
src/components/Discounts/Discounts.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx
src/components/Form/ValidationSchemas.ts
src/components/OperatorConvention/Discount.tsx
src/utils/strings.tsx

This PR is related to https://github.com/pagopa/cgn-onboarding-portal-backend/pull/73

[#PE-176] Allow nullable discount value

---

package.json
src/components/Form/ValidationSchemas.ts

This PR allows to set a discount value within 1-100 range.

[#PE-179] Change discount range

---

src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx

This PR is related to https://github.com/pagopa/cgn-onboarding-portal-backend/pull/75

[#PE-180] Remove discount range dates delay

---

package.json
src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx
src/components/Form/CreateProfileForm/DiscountData/ProductCategories.tsx
src/utils/strings.tsx

This PR allows to show new Product categories and it is related to https://github.com/pagopa/cgn-onboarding-portal-backend/pull/76

[#PE-178] Allow new product categories visualization

---

package.json
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx
src/components/Form/ValidationSchemas.ts
src/utils/form_types.tsx

This PR adds allNationalAddresses field that allows to save an empty address list for Physical operators' type.

[#PE-174] Add All National Addresses field

---

src/IDPS.ts

This PR fixes the SPID idps images broken uris

[PE-190] Fix SPID broken uris

---

src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/ToggleField.tsx

This PR fixes the unformated fullAddress attribute causing form submission fail and UI spacing on toggle component

[PE-191] Fixes unformatted fullAddress field

---

src/components/Discounts/ImportationStatus.tsx

[PE-238] Implements a starting loading state for polling component

---

src/api/api.yaml
src/api/api_backoffice.yaml
src/components/Form/CreateProfileForm/ProfileData/SalesChannelDiscountCodeType.tsx

Fiscal code can be any string between 4 and 20 chars.

Relaxed fiscal code for legal representative

---

src/components/Discounts/DiscountDetailRow.tsx
src/components/OperatorConvention/Discount.tsx

Adds discount url visualization on discount summary informations

[PE-271] Display discountUrl on discount summary informations

---

src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx

This PR Fixes the discountUrl validation failure caused by null value

[PE-273] Fixes discountUrl validation

---

src/components/Discounts/DiscountDetailRow.tsx
src/components/Discounts/Discounts.tsx
src/components/Discounts/SuspendModal.tsx

This PR implements the suspend discount feature

Implements suspend discount feature

---

src/components/Form/HelpForm/ReCAPTCHAFormComponent.tsx

This PR is aimed to use recaptcha.net source instead of google Recaptcha

Implements handler to use recaptcha.net

---

.env.production

This PR aims to fix the redirect on admin access for Production environment

Fixes config on Prod for admin login

---

src/components/Discounts/DiscountDetailRow.tsx
src/components/Discounts/Discounts.tsx
src/components/Discounts/UnpublishModal.tsx

This PR changes all occurences by operator section from suspend action to unpublish one.

[PE-289] Refactors suspend to unpublish

---

package.json
src/api/backoffice.ts
src/components/Form/ActivationForm.tsx
src/components/Form/CreateActivationForm/CreateActivationForm.tsx
src/components/Form/EditActivationForm/EditActivationForm.tsx
src/components/Form/ValidationSchemas.ts
src/components/OperatorActivations/OperatorActivationDetail.tsx
src/components/OperatorActivations/OperatorActivations.tsx

This PR aims to fix validation schemas for new AttributeAuthority form implementation and introduces minor improvements on url validation

Fixes admin panel

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a default template for new pull requests thread

chore: Add default pull request template

---

src/components/Form/CreateProfileForm/DiscountData/Bucket.tsx

Change number label 1M to 10k
• go to Agevolazioni -> Nuova agevolazione 
• scroll to bottom and show new message changed in 
_Carica la lista di codici sconto*
Caricare un file .CSV con la lista di almeno 10.000 di codici sconto statici relativi all’agevolazione.
Per maggiori informazioni, consultare la [Documentazione tecnica](https://pagopa.gitbook.io/documentazione-tecnica-portale-operatori-1.0.0) o scaricare il [file di esempio](http://localhost:3000/test-codes.84523c23.csv)_

chore: change number label 1m to 10k

---

src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx

change description in "Nome Operatore visualizzato"
To show new label go to Dati operatore -> Modifica dati
and switch "Vuoi visualizzare un nome diverso dentro l’app?"

chore: [PE-402] change label description in "Dati operatore"

---

src/components/Form/CreateProfileForm/DiscountData/LandingPage.tsx
src/components/Form/ValidationSchemas.ts

referrer parameter in landing page is optional
- Login as operator
- Chose bucket code
- Create (agevolazione)
- Save without filling the field "Inserire il valore del parametro referrer da trasmettere alla landing page"

chore:  referrer parameter in landing page is optional

---

README.md

This PR adds a more detailed instruction to startup the project in local environment

docs: Add a detailed readme to startup the project

---

src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx

This PR fixes the max selectable categories value into onboarding stepper form
Login with a drafted operator with an onboarding process pending and create a new discount choosing more than one category

fix: product categories variable in onboarding form

---

.vscode/settings.json
src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx
src/components/Form/EditProfileForm/EditProfileForm.tsx
src/components/Form/SupportContact.tsx
src/components/Form/ValidationSchemas.ts
src/components/ProfileData/ProfileData.tsx
src/navigation/RouterConfig.tsx

Add support contact to operator form (create and edit)
- Add contact type and value to operator data edit form
- Add contact type and value to operator data onboarding form
- login with an onboarded user and edit his data (the added section is the last)
- login with a not yet onboarded user, the new section is at the bottom of the second step

feat: [PE-426] Add support contact to operator form (create and edit)

---

src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/CreateProfileForm/ProfileData/ReferentData.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx
src/components/Form/EditProfileForm/EditProfileForm.tsx
src/components/Form/FormSection.tsx
src/components/Form/ValidationSchemas.ts
src/components/Profile/Profile.tsx

Possibility to add up to 4 secondary referentezs
- add up to 4 secondary referents beside the main
- profile -> edit data -> last section
- onboarding -> 2nd step
- profile last section (readonly)
Try editing referents in the sections mentioned above

[PE-430] secondary referents

---

src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx

This PR fixes the support value and support type with default values

fix: Restore the support value as default

---

src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx
src/components/Form/EditOperatorDataForm/EditOperatorDataForm.tsx

This PR fixes a bug in production about the supportType and supportValue default values;

fix: hotfix for support value as default value

---

package.json
src/components/Form/ValidationSchemas.ts

added validation for landing page, it now requires protocol (mainly needed for ios app)
- landing page url validation on creation of new discount
- landing page url validation on creation of new discounts during onboarding
- test new discount
- login as onboarded merchant
- create new discount
- in the field named "landing page" try inserting invalid url or url without protocol
- test new discount during onboarding
- login as not yet onboarder merchant
- progress the wizard until discounts section (step 3)
- in the field named "landing page" try inserting invalid url or url without protocol

[PE-493]: landing page url requires protocol

---

src/components/Discounts/Discounts.tsx
src/components/Form/ActivationForm.tsx
src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx
src/components/Form/CreateProfileForm/Documentation/Documentation.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/ReferentData.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx
src/components/Form/SupportContact.tsx
src/components/Introduction/Introduction.tsx
src/components/OperatorConvention/ConventionDetails.tsx
src/components/Profile/ProfileDocuments.tsx
src/components/Requests/RequestsDetails.tsx
src/pages/Dashboard.tsx

label fixes
- see https://docs.google.com/spreadsheets/d/1RLnyyN1BuBNuYNc9TEu4el7wlLdnqhyTMpzsYrafruw/edit#gid=0
Test all screens https://www.figma.com/file/XShwT2jc7MlMX6NLszlx4P/Portale-Esercenti?node-id=2179%3A39396&mode=dev
refer to updates in https://docs.google.com/spreadsheets/d/1RLnyyN1BuBNuYNc9TEu4el7wlLdnqhyTMpzsYrafruw/edit#gid=0

Pe 556 public entitites fix 1

---

src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Introduction/Introduction.tsx
src/components/OperatorConvention/Profile.tsx
src/pages/Dashboard.tsx

Copy change for adress in onboarding
- different based on public/private entity
go tithe third screen of wizard

PE-567-adress-copy

---

src/components/Form/CreateProfileForm/Documents/Documents.tsx
src/components/Profile/ProfileDocuments.tsx

Public entitties needs 1 document, private 2, this is the implementaiton
- In the last page of onboarding wizard, the operator must upload only 1 document insted of two if it is a public eneitty
Complete the convention request wizard for both public and private operators

PE-561 public entity documents

---

src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannelDiscountCodeType.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/ValidationSchemas.ts

removed sales channel type select for private entities
Test on the second tab of onboarding for both public and private operators

PE-574 sales channel type

---

src/components/Form/CreateProfileForm/DiscountData/LandingPage.tsx
src/components/Form/ValidationSchemas.ts

Reverts pagopa/cgn-onboarding-portal-frontend#217
https://pagopa.atlassian.net/browse/PE-713

Revert "chore:  referrer parameter in landing page is optional"

---

CODEOWNERS

Update CODEOWNERS adding @freddi301

---

src/components/Discounts/Discounts.tsx
src/components/Form/CreateProfileForm/DiscountData/Bucket.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/Documents/FileRow.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx
src/utils/chainAxios.tsx

New error codes had been added on backend. This PR adds necessary visual feedback in form of tooltips.
- use new method `normalizeAxiosResponse` in impacted call sites
- add and update error messages as specified
- login come operatore onboarded
- crea nuova opportunità
- apri tab con il dettaglio opportunità aperto con il bottone "test" visibile
- in un latro tab (disabilita le righe 141, 145,146 in DiscountInfo.tsx) mettendo delle date precedenti ad oggi
- torna nel primo tab e clicca su test
- ora dovrebbe uscire tooltip di errore 
- login come operatore non ancora onboarded
- al 4 step el wizard carica un file diverso da pdf (forse disabilita riga 174 se il browser non lo permette)
- dovrebbe postarsi tooltip di errore
- login con operatore che non ha completato il wizard
- al secondo …

[PE-711] Add new error tooltips

---

src/components/Form/CreateProfileForm/ProfileData/ProfileData.tsx

Because of how backend endpoints are organized, there are endpoint to create and update a merchant.
There is an edge case where the frontend ends up calling createProfile when a profile was already created, so this PR checks this edge case and calls updateProfile instead.
- modified call site for Ajax call
- login with a merchant that has not done any steps in the onboarding wizards
- open two tabs
- complete the second step in the first tab
- complete the second step in the second tab
- completing the second step in the second step should go fine with this PR meanwhile it resulted in error before

[PE-828] Fix operator created edge case

---

src/components/Discounts/DiscountDetailRow.tsx
src/components/Discounts/Discounts.tsx

Add alert to discounts list screen when max published discounts limit is reached.
- add alert
- disable publish button
Login as an operator.
Create and advance to published state 5 discounts.
Now the alert should appear and publish button should be disabled.

feat: [PE-837] Max published discounts check

---

src/components/Callout/Callout.tsx
src/components/Discounts/DiscountDetailRow.tsx
src/components/Discounts/Discounts.tsx

add "Modifica opportunià" button on alert for suspended discounts
- add button
- tweak alert component
- fix expand button
- login as an operator
- go to discount list
- expand the detail of a suspended discount
- there should be the button

feat: [PE-774] add "Modifica opportunià" button on alert for suspended discounts

---

src/components/Form/CreateDiscountForm/CreateDiscountForm.tsx
src/components/Form/CreateProfileForm/DiscountData/Bucket.tsx
src/components/Form/CreateProfileForm/DiscountData/DiscountData.tsx
src/components/Form/CreateProfileForm/DiscountData/EnrollToEyca.tsx
src/components/Form/EditDiscountForm/EditDiscountForm.tsx

Update label for eyca participation form field checkbox.
The field is in all screens related to creating or editing discounts.

fix: [PE-829] Update label for eyca participation

---

.devops/code-review-pipelines.yml

This PR removes DangerJS since it's banned by PagoPA company security policy

ci: Removed DangerJS due company policy

---

CODEOWNERS

This PR adds @LeleDallas as codeowner

chore: Update CODEOWNERS adding @LeleDallas

---

src/pages/Login.tsx

This PR disables the maintenance banner shown in the login page.

chore: Disable maintenance banner

---

src/pages/Login.tsx

Remove maintenance banner
- Set default value of the `MAINTENANCE_BANNER` constant from `"short-downtime"` to `undefined`
Open landing page. there should not be a maintenance banner

chore: update maintenance banner flag

---

src/components/Form/CreateProfileForm/ProfileData/SalesChannelDiscountCodeType.tsx

This PR edits the sales channels docs link redirect with the new ones from the developer portal.
- Replaced the previous docs link URL with the new ones from the developer portal pagoPA site.
- Creates a new discount with any merchant and verifies that the href links function correctly when selecting the discount type.

chore: [IOBP-1547] Edit sales channels docs link

---

src/components/Form/CreateProfileForm/ProfileData/ProfileImage.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/ReferentData.tsx
src/components/Form/FormSection.tsx

This PR adds some content review enhancements provided by design.
- Edited some texts with the reviewed copy label.

fix: [IOBP-1656,IOBP-1661,IOBP-1657,IOBP-1658,IOBP-1659] Content review enhancement

---

src/components/Form/ActivationForm.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannelDiscountCodeType.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/FormSection.tsx
src/pages/CreateProfile.tsx

This pull request improves the user interface text
- Edited some texts with the reviewed copy label.
- Enhanced the `description` prop type to accept either a `string` or a `ReactElement`, enabling richer content such as links or styled text.

fix: [IOBP-1662,IOBP-1663,IOBP-1654,IOBP-1655] Content review enhancement

---

src/components/Form/CreateProfileForm/Documentation/Documentation.tsx
src/pages/CreateProfile.tsx

This PR removes useless `Annulla` from `Leggi la documentazione` section
- Simplified the `Documentation` component by removing the `Link` button for cancellation
Ensure that `Annulla` button is not present anymore
https://github.com/user-attachments/assets/9e0d0c87-8291-4abe-a8c4-e25771013e3d

fix: [IOBP-1653] Remove useless `Annulla` button

---

src/components/Form/CreateProfileForm/Documentation/Documentation.tsx
src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannelDiscountCodeType.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/OperatorConvention/OperatorData.tsx

This pull request improves the user interface text
- Edited some texts with the reviewed copy label.
Ensure text is aligned with design requirements

fix: [IOBP-1671,IOBP-1673,IOBP-1678] Update copy content

---

src/components/Form/CreateProfileForm/DiscountData/StaticCode.tsx

This pull request includes a placeholder text, "Inserisci codice statico," added to the `Field` component to improve user guidance.
Ensure that now the placeholder is visible

fix: [IOBP-1666] Add missing form item placeholder

---

src/authentication/authentication.ts

There is a corner case when third party authentication redirects the user back to our website.
The UI requirement for this case is to redirect to login page.
- redirect to login page
In UAT envornment, begin theb login as non admin user.
Case A, type in wrong password 3 times, then click on "chiudi" button on next page, it should redirect to our login route (inbstead of haning on login in progress screen)
Case B, click on "annulla login", same as above

chore: [IOBP-1670] add: redirect to login page on login error

---

src/components/AgreementState/AgreementState.tsx
src/pages/Dashboard.tsx
src/store/agreement/agreementSlice.ts

Remove convention end date
- removed date label
Login as non admin
Select a merchant that was already approved
Check on top right rectangle that there is no more end date in the agreement status

chore: [IOBP-1694] remove convention end date

---

src/components/Form/CreateProfileForm/DiscountData/DiscountInfo.tsx
src/styles/react-datepicker-custom.scss

Add year/month navigation to calendar input.
- add year dropdown
- add month dropdown
- changed font for calendar input
- fixed dropdown header issues
Create or modify any discount, the check the start/end date inputs dropdown. Calendar input is present only in those forms and fields

chore: [IOBP-1705] add calendar input navigation

---

src/components/Form/CreateProfileForm/ProfileData/ProfileInfo.tsx
src/components/Form/CreateProfileForm/ProfileData/SalesChannels.tsx
src/components/Form/FormField.tsx
src/components/Form/HelpForm/HelpForm.tsx
src/components/Form/ToggleField.tsx

Changed form control margins to 24px
Impacted forms are:
- onboarding forms
- step 2
- step 3
- onboarded non admin user forms:
- edit "Dati profilo"
- edit "Dati ente"
- create discount
- edit discount
- help form
- admin forms
- "aggiungi operatore"
- "modifica operatore"

chore: [IOBP-1714] fix form spacing
